name: ${project.name}
version: ${project.version}
api-version: 1.13
description: ${project.description}
author: Chris Naude
main: com.cnaude.dynwarp.DynWarp
depend: [ dynmap ]
commands:
    dwarplist:
        description: List Dynmap marker warps.
        usage: /<command>
        aliases: [ dwl ]
    dwarp:
        description: Warp to a Dynmap marker with optional direction (n, s, e, w)
        usage: /<command> [marker] ([direction)]
        aliases: [ dw ]
permissions: 
    dynwarp.tp:
        description: Gives player access to /dwarp and /dw.
        default: op 
    dynwarp.list:
        description: Gives player access to /dwarplist and /dwl.
        default: op 
